name: Uptime Checker on Push

# Workflow akan berjalan setiap kali ada push ke branch tertentu
on:
  push:
    branches:
      - main # Ganti dengan nama branch yang sesuai jika berbeda
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual melalui GitHub UI

jobs:
  check-uptime:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Jalankan uptime checker
      - name: Run Uptime Checker
        run: |
          python uptime_checker.py
